import 'dart:collection';

import 'package:flutter/material.dart';
import 'package:flutter_nft/models/friend.dart';

class FriendRepository extends ChangeNotifier {
  List<Friend> _friends = [];

  UnmodifiableListView<Friend> get friends => UnmodifiableListView(_friends);

  insert(Friend friend) {
    _friends.add(friend);
    notifyListeners();
  }

  FriendRepository() {
    _friends = [
      Friend(
        id: 1,
        background: const Color(0XFFF2DAC7),
        eyes: 'Nose glasses',
        hat: 'Visor',
        leftArm: 'Umbrella',
        rightArm: 'Pocket',
        upperBody: 'Pink Zipper',
        sleeves: 'Long Sleeves',
        legs: 'Tan Shorts',
        feet: 'Dark Blue',
        value: 35.94,
      ),
      Friend(
        id: 2,
        background: const Color(0XFFD0CCF5),
        eyes: 'Nerd Ghost glasses',
        hat: '-',
        leftArm: 'Skate',
        rightArm: 'Swinging',
        upperBody: 'Blue Thurtleneck',
        sleeves: 'Long Sleeves',
        legs: 'Dark Blue Pants',
        feet: 'Pink Slippers',
        value: 27.55,
      ),
      Friend(
        id: 3,
        background: const Color(0XFFF8CFF1),
        eyes: 'Brown glasses',
        hat: 'Blue Bucket',
        leftArm: 'Swinging',
        rightArm: 'Basketball',
        upperBody: 'White Loose',
        sleeves: 'Long Sleeves',
        legs: 'Tan Pants',
        feet: 'Black Shoes',
        value: 15.90,
      ),
      Friend(
        id: 4,
        background: const Color(0XFFC1D7E5),
        eyes: 'White Nerd glasses',
        hat: '-',
        leftArm: 'Baseball Bat',
        rightArm: 'Swinging',
        upperBody: 'Black Yellow',
        sleeves: 'Long Sleeves',
        legs: 'Green Pants',
        feet: 'Bunny Slippers',
        value: 31.14,
      ),
      Friend(
        id: 5,
        background: const Color(0XFFD0CCF5),
        eyes: 'Black glasses',
        hat: '-',
        leftArm: 'Swinging',
        rightArm: 'Swinging',
        upperBody: 'Light Dark Blue',
        sleeves: 'Long Sleeves',
        legs: 'Grey Pants',
        feet: 'Blue Shoes',
        value: 32.4,
      ),
      Friend(
        id: 6,
        background: const Color(0XFFF2DAC7),
        eyes: 'Black Nerd glasses',
        hat: '-',
        leftArm: 'Swinging',
        rightArm: 'Swinging',
        upperBody: 'Grey White V-neck',
        sleeves: 'Long Sleeves',
        legs: 'Green Sweetpants',
        feet: 'Light Blue',
        value: 25.94,
      ),
      Friend(
        id: 7,
        background: const Color(0XFFF6D9C5),
        eyes: 'White Nerd glasses',
        hat: 'Detective Hat',
        leftArm: 'Swinging',
        rightArm: 'Metal Detector',
        upperBody: 'Yeloow Blue Jacket',
        sleeves: 'Long Sleeves',
        legs: 'Dark Blue Pants',
        feet: 'Maroom Shoes',
        value: 32.28,
      ),
      Friend(
        id: 8,
        background: const Color(0XFFF7F2BC),
        eyes: 'Googly Eyes',
        hat: 'White Headband',
        leftArm: 'Swinging',
        rightArm: 'Swinging',
        upperBody: 'Grey Belted Coat',
        sleeves: 'Long Sleeves',
        legs: 'Naked',
        feet: 'Pink Slippers',
        value: 26.1,
      ),
      Friend(
        id: 9,
        background: const Color(0XFFCFF0CF),
        eyes: '-',
        hat: 'Rain Hat',
        leftArm: 'Sticky Bag',
        rightArm: 'Swinging',
        upperBody: 'Grey White V-Neck',
        sleeves: 'Long Sleeves',
        legs: 'Green Pants',
        feet: 'Black Shoes',
        value: 30.8,
      ),
      Friend(
        id: 10,
        background: const Color(0XFFF8CFF1),
        eyes: 'Black Nerd glasses',
        hat: '-',
        leftArm: 'Swinging',
        rightArm: 'Swinging',
        upperBody: 'Grey Zipper',
        sleeves: 'Long Sleeves',
        legs: 'Light Blue Shorts',
        feet: 'Red Shoes',
        value: 40.14,
      ),
      Friend(
        id: 11,
        background: const Color(0XFFF6D9C5),
        eyes: '-',
        hat: 'Tan Baseball',
        leftArm: 'Fishing pPole',
        rightArm: 'Swinging',
        upperBody: 'Green White Jacket',
        sleeves: 'Long Sleeves',
        legs: 'Black Blue Skirt',
        feet: 'Ice Grey Shoes',
        value: 50.25,
      ),
    ];
  }
}
